#!/usr/bin/env bash

status=$(openvpn status | head -n1 | awk '{print $2}')

if [ "$status" == "Connected" ]; then 
	kitty -e sudo openvpn d
	echo "#90c861" > /tmp/eww/vpnstat-hex
else 
	kitty -e sudo openvpn c
	echo "#D35D6E" > /tmp/eww/vpnstat-hex
fi
