- 1.1.8
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, divert-crown, crown-smooth, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4096
  _dpi-sliding: 16
  _modelId: B02340820000
  _sensitive: {change-host: true, divert-keys: true, dpi: true, dpi-sliding: true, hires-scroll-mode: true, hires-smooth-invert: true, mouse-gestures: true,
    reprogrammable-keys: true, smart-shift: true, thumb-scroll-invert: true, thumb-scroll-mode: true}
  _serial: 444FC285
  _unitId: 444FC285
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 2, 196: 0}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 8
  thumb-scroll-invert: false
  thumb-scroll-mode: false
